lib/book_club_poll_web/router.ex
defmodule BookClubPollWeb.Router do
  use BookClubPollWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {BookClubPollWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BookClubPollWeb do
    pipe_through :browser

    live "/", PageLive, :index

    live "/polls", PollLive.Index, :index
    live "/polls/new", PollLive.Index, :new
    live "/polls/:id/edit", PollLive.Index, :edit
    live "/polls/:id", PollLive.Show, :show
    live "/polls/:id/show/edit", PollLive.Show, :edit

    live "/ballots", BallotLive.Index, :index
    live "/ballots/new", BallotLive.Index, :new
    live "/ballots/:id/edit", BallotLive.Index, :edit
    live "/ballots/:id", BallotLive.Show, :show
    live "/ballots/:id/show/edit", BallotLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", BookClubPollWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: BookClubPollWeb.Telemetry
    end
  end
end

lib/book_club_poll_web/live/ballot_live/form_component.ex
defmodule BookClubPollWeb.BallotLive.FormComponent do
  use BookClubPollWeb, :live_component

  alias BookClubPoll.Ballots

  @impl true
  def update(%{ballot: ballot} = assigns, socket) do
    changeset = Ballots.change_ballot(ballot)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"ballot" => ballot_params}, socket) do
    changeset =
      socket.assigns.ballot
      |> Ballots.change_ballot(ballot_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"ballot" => ballot_params}, socket) do
    save_ballot(socket, socket.assigns.action, ballot_params)
  end

  defp save_ballot(socket, :edit, ballot_params) do
    case Ballots.update_ballot(socket.assigns.ballot, ballot_params) do
      {:ok, _ballot} ->
        {:noreply,
         socket
         |> put_flash(:info, "Ballot updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_ballot(socket, :new, ballot_params) do
    case Ballots.create_ballot(ballot_params) do
      {:ok, _ballot} ->
        {:noreply,
         socket
         |> put_flash(:info, "Ballot created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/book_club_poll_web/live/ballot_live/index.ex
defmodule BookClubPollWeb.BallotLive.Index do
  use BookClubPollWeb, :live_view

  alias BookClubPoll.Ballots
  alias BookClubPoll.Ballots.Ballot

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :ballots, list_ballots())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Ballot")
    |> assign(:ballot, Ballots.get_ballot!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Ballot")
    |> assign(:ballot, %Ballot{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Ballots")
    |> assign(:ballot, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    ballot = Ballots.get_ballot!(id)
    {:ok, _} = Ballots.delete_ballot(ballot)

    {:noreply, assign(socket, :ballots, list_ballots())}
  end

  defp list_ballots do
    Ballots.list_ballots()
  end
end

lib/book_club_poll_web/live/ballot_live/show.ex
defmodule BookClubPollWeb.BallotLive.Show do
  use BookClubPollWeb, :live_view

  alias BookClubPoll.Ballots

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:ballot, Ballots.get_ballot!(id))}
  end

  defp page_title(:show), do: "Show Ballot"
  defp page_title(:edit), do: "Edit Ballot"
end

lib/book_club_poll_web/live/live_helpers.ex
defmodule BookClubPollWeb.LiveHelpers do
  import Phoenix.LiveView.Helpers

  @doc """
  Renders a component inside the `BookClubPollWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal @socket, BookClubPollWeb.PollLive.FormComponent,
        id: @poll.id || :new,
        action: @live_action,
        poll: @poll,
        return_to: Routes.poll_index_path(@socket, :index) %>
  """
  def live_modal(socket, component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(socket, BookClubPollWeb.ModalComponent, modal_opts)
  end
end

lib/book_club_poll_web/live/modal_component.ex
defmodule BookClubPollWeb.ModalComponent do
  use BookClubPollWeb, :live_component

  @impl true
  def render(assigns) do
    ~L"""
    <div id="<%= @id %>" class="phx-modal"
      phx-capture-click="close"
      phx-window-keydown="close"
      phx-key="escape"
      phx-target="#<%= @id %>"
      phx-page-loading>

      <div class="phx-modal-content">
        <%= live_patch raw("&times;"), to: @return_to, class: "phx-modal-close" %>
        <%= live_component @socket, @component, @opts %>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
end

lib/book_club_poll_web/live/page_live.ex
defmodule BookClubPollWeb.PageLive do
  use BookClubPollWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, query: "", results: %{})}
  end

  @impl true
  def handle_event("suggest", %{"q" => query}, socket) do
    {:noreply, assign(socket, results: search(query), query: query)}
  end

  @impl true
  def handle_event("search", %{"q" => query}, socket) do
    case search(query) do
      %{^query => vsn} ->
        {:noreply, redirect(socket, external: "https://hexdocs.pm/#{query}/#{vsn}")}

      _ ->
        {:noreply,
         socket
         |> put_flash(:error, "No dependencies found matching \"#{query}\"")
         |> assign(results: %{}, query: query)}
    end
  end

  defp search(query) do
    if not BookClubPollWeb.Endpoint.config(:code_reloader) do
      raise "action disabled when not in development"
    end

    for {app, desc, vsn} <- Application.started_applications(),
        app = to_string(app),
        String.starts_with?(app, query) and not List.starts_with?(desc, ~c"ERTS"),
        into: %{},
        do: {app, vsn}
  end
end

lib/book_club_poll_web/live/poll_live/form_component.ex
defmodule BookClubPollWeb.PollLive.FormComponent do
  use BookClubPollWeb, :live_component

  alias BookClubPoll.Polls

  @impl true
  def update(%{poll: poll} = assigns, socket) do
    changeset = Polls.change_poll(poll)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"poll" => poll_params}, socket) do
    changeset =
      socket.assigns.poll
      |> Polls.change_poll(poll_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"poll" => poll_params}, socket) do
    save_poll(socket, socket.assigns.action, poll_params)
  end

  defp save_poll(socket, :edit, poll_params) do
    case Polls.update_poll(socket.assigns.poll, poll_params) do
      {:ok, _poll} ->
        {:noreply,
         socket
         |> put_flash(:info, "Poll updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_poll(socket, :new, poll_params) do
    case Polls.create_poll(poll_params) do
      {:ok, _poll} ->
        {:noreply,
         socket
         |> put_flash(:info, "Poll created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/book_club_poll_web/live/poll_live/index.ex
defmodule BookClubPollWeb.PollLive.Index do
  use BookClubPollWeb, :live_view

  alias BookClubPoll.Polls
  alias BookClubPoll.Polls.Poll

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :polls, list_polls())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Poll")
    |> assign(:poll, Polls.get_poll!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Poll")
    |> assign(:poll, %Poll{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Polls")
    |> assign(:poll, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    poll = Polls.get_poll!(id)
    {:ok, _} = Polls.delete_poll(poll)

    {:noreply, assign(socket, :polls, list_polls())}
  end

  defp list_polls do
    Polls.list_polls()
  end
end

lib/book_club_poll_web/live/poll_live/show.ex
defmodule BookClubPollWeb.PollLive.Show do
  use BookClubPollWeb, :live_view

  alias BookClubPoll.Polls

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:poll, Polls.get_poll!(id))}
  end

  defp page_title(:show), do: "Show Poll"
  defp page_title(:edit), do: "Edit Poll"
end

lib/book_club_poll_web/live/poll_live/form_component.html.leex
<h2><%= @title %></h2>

<%= f = form_for @changeset, "#",
  id: "poll-form",
  phx_target: @myself,
  phx_change: "validate",
  phx_submit: "save" %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :description %>
  <%= textarea f, :description %>
  <%= error_tag f, :description %>

  <%= label f, :number_to_rank %>
  <%= number_input f, :num_ranks %>
  <%= error_tag f, :num_ranks %>

  <%= label f, :end_date %>
  <%= date_select f, :end_date %>
  <%= error_tag f, :end_date %>

    <p class="mt-4 mb-2 font-bold">Books</p>

    <%= inputs_for f, :poll_book_options, fn b -> %>
      <div class="flex flex-wrap -mx-1 overflow-hidden">
        <div class="form-group px-1 w-3/6">
          <%= label b, :name %>
          <%= text_input b, :name, class: "form-control" %>
          <%= error_tag b, :name %>
        </div>

        <div class="form-group px-1 w-2/6">
          <%= label b, :url %>
          <%= text_input b, :url, class: "form-control" %>
          <%= error_tag b, :url %>
        </div>

        <div class="form-group px-1 w-1/6">
          <%= label b, :delete %><br>
          <%= if is_nil(b.data.temp_id) do %>
            <%= checkbox b, :delete %>
          <% else %>
            <%= hidden_input b, :temp_id %>
            <a href="#" phx-click="remove-variant" phx-value-remove="<%= b.data.temp_id %>">&times</a>
          <% end %>
        </div>
      </div>
    <% end %>

    <a href="#" phx-click="add-variant">Add book</a>
    <br />

  <%= submit "Save", phx_disable_with: "Saving..." %>
</form>

lib/book_club_poll_web/live/poll_live/index.html.leex
<h1>Listing Polls</h1>

<%= if @live_action in [:new, :edit] do %>
  <%= live_modal @socket, BookClubPollWeb.PollLive.FormComponent,
    id: @poll.id || :new,
    title: @page_title,
    action: @live_action,
    poll: @poll,
    return_to: Routes.poll_index_path(@socket, :index) %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Number to Rank</th>
      <th>End date</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="polls">
    <%= for poll <- @polls do %>
      <tr id="poll-<%= poll.id %>">
        <td><%= poll.name %></td>
        <td><%= poll.description %></td>
        <td><%= poll.num_ranks %></td>
        <td><%= poll.end_date %></td>

        <td>
          <span><%= live_redirect "Show", to: Routes.poll_show_path(@socket, :show, poll) %></span>
          <span><%= live_patch "Edit", to: Routes.poll_index_path(@socket, :edit, poll) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: poll.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= live_patch "New Poll", to: Routes.poll_index_path(@socket, :new) %></span>

lib/book_club_poll_web/live/poll_live/show.html.leex
<h1>Show Poll</h1>

<%= if @live_action in [:edit] do %>
  <%= live_modal @socket, BookClubPollWeb.PollLive.FormComponent,
    id: @poll.id,
    title: @page_title,
    action: @live_action,
    poll: @poll,
    return_to: Routes.poll_show_path(@socket, :show, @poll) %>
<% end %>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @poll.name %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @poll.description %>
  </li>

  <li>
    <strong>Number to Rank:</strong>
    <%= @poll.num_ranks %>
  </li>

  <li>
    <strong>End date:</strong>
    <%= @poll.end_date %>
  </li>

</ul>

<span><%= live_patch "Edit", to: Routes.poll_show_path(@socket, :edit, @poll), class: "button" %></span>
<span><%= live_redirect "Back", to: Routes.poll_index_path(@socket, :index) %></span>